Add android app
davidlunadeleon/seguimiento-de-sintomas-app pull request #1
Opened 2021-11-08 07:10 UTC by CharlesGovea

Initial commit to add the base Android project files and add Git VCS to the project pn Android Studio.

2021-11-08 17:47 UTC, betorendon approved these changes

2021-11-08 20:54 UTC, davidlunadeleon requested changes

2021-11-08 20:54 UTC, davidlunadeleon commented on app/build.gradle
> +    id 'com.android.application'
¿No falta aquí la configuración del plugin `com.google.gms.google-services` y las demás asociadas a agregar firebase?

2021-11-08 20:54 UTC, davidlunadeleon commented on app/build.gradle
> +        applicationId "com.a00819647.seguimientodesintomas"
¿No se supone que el nombre debería ser `com.example.sintomasapp`? Lo mismo para cuando se especifica el package name.

2021-11-09 02:14 UTC, davidlunadeleon approved these changes

2021-11-09 02:14 UTC, merged